FORMATTERS_DISABLE_ERRORS: false

DISABLE_LINTERS:
  - JAVASCRIPT_STANDARD
  - MARKDOWN_MARKDOWNLINT
  - MARKDOWN_MARKDOWN_TABLE_FORMATTER
  - REPOSITORY_DEVSKIM
  - TYPESCRIPT_STANDARD

# ESLint
JAVASCRIPT_ES_CLI_EXECUTABLE:
  - node_modules/.bin/eslint
TYPESCRIPT_ES_CLI_EXECUTABLE:
  - node_modules/.bin/eslint

# jscpd
COPYPASTE_JSCPD_ARGUMENTS: "--threshold 10"

# kingfisher
REPOSITORY_KINGFISHER_ARGUMENTS: "--exclude node_modules"

# shfmt
BASH_SHFMT_ARGUMENTS: "--indent 2 -case-indent"

# trivy
REPOSITORY_TRIVY_ARGUMENTS: "--ignorefile ./.trivyignore.yaml"

# zizmor
ACTION_ZIZMOR_UNSECURED_ENV_VARIABLES:
  - GITHUB_TOKEN
