misconfigurations:
  - id: AVD-DS-0002
    paths:
      - tools/tests/fixtures/minimal-image/Dockerfile
    statement: USER not needed for this test Dockerfile
  - id: AVD-DS-0026
    paths:
      - tools/tests/fixtures/minimal-image/Dockerfile
    statement: HEALTHCHECK not needed
